{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-apache-apache-server
  namespace: apache-namespace
spec:
  ingressClassName: nginx
  rules:
    - host: mijn-apache.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-apache-apache-server-service
                port:
                  number: 80
{{- end }}
