apiVersion: v1
kind: Service
metadata:
  name: {{ include "apache-server.fullname" . }}-service
  labels:
    {{- include "apache-server.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app.kubernetes.io/instance: my-apache
