---
- name: Install WordPress on containers
  hosts: all
  become: yes
  vars:
    wordpress_db_name: wordpress
    wordpress_db_user: wp_user
    wordpress_db_password: strongpassword
    wordpress_db_host: localhost
    wordpress_site_url: "http://{{ inventory_hostname }}"
    wordpress_site_title: "My WordPress Site"
    wordpress_admin_user: admin
    wordpress_admin_password: adminpassword
    wordpress_admin_email: admin@example.com

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages (Apache, MySQL, PHP, and Curl)
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - libapache2-mod-php
          - php-cli
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - curl
          - wget
        state: present

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: true

    - name: Start and enable MySQL
      service:
        name: mysql
        state: started
        enabled: true

    - name: Create WordPress MySQL database
      mysql_db:
        name: "{{ wordpress_db_name }}"
        state: present

    - name: Create WordPress MySQL user
      mysql_user:
        name: "{{ wordpress_db_user }}"
        password: "{{ wordpress_db_password }}"
        priv: "{{ wordpress_db_name }}.*:ALL"
        host: "{{ wordpress_db_host }}"
        state: present

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/latest.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/latest.tar.gz
        dest: /var/www/html/
        remote_src: yes

    - name: Rename extracted WordPress folder if necessary
      command: mv /var/www/html/wordpress/* /var/www/html/
      args:
        removes: /var/www/html/wp-config-sample.php

    - name: Set proper permissions for WordPress
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Create wp-config.php
      copy:
        dest: /var/www/html/wp-config.php
        content: |
          <?php
          define('DB_NAME', '{{ wordpress_db_name }}');
          define('DB_USER', '{{ wordpress_db_user }}');
          define('DB_PASSWORD', '{{ wordpress_db_password }}');
          define('DB_HOST', '{{ wordpress_db_host }}');
          define('WP_SITEURL', '{{ wordpress_site_url }}');
          define('WP_HOME', '{{ wordpress_site_url }}');
          define('FS_METHOD', 'direct');
          ?>
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Enable Apache rewrite module
      command: a2enmod rewrite

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Check if WordPress is accessible
      uri:
        url: "http://localhost"
        status_code: 200
