---
- hosts: localhost
  become: yes
  connection: local
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install required packages for WordPress
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - libapache2-mod-php
          - wget
        state: present

    - name: Enable Apache rewrite module
      command: a2enmod rewrite

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted

    - name: Download WordPress
      shell: |
        wget https://wordpress.org/latest.tar.gz -O /tmp/latest.tar.gz
        tar -xvzf /tmp/latest.tar.gz -C /var/www/html --strip-components=1
      args:
        creates: /var/www/html/wp-config-sample.php

    - name: Set permissions on WordPress files
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes

    - name: Create MySQL database for WordPress
      mysql_db:
        name: wordpress
        state: present

    - name: Create MySQL user for WordPress
      mysql_user:
        name: wordpress_user
        password: wordpress_password
        priv: 'wordpress.*:ALL'
        state: present

    - name: Configure wp-config.php
      copy:
        src: /var/www/html/wp-config-sample.php
        dest: /var/www/html/wp-config.php
        remote_src: yes

    - name: Update wp-config.php with database information
      lineinfile:
        path: /var/www/html/wp-config.php
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: 'database_name_here', line: "define( 'DB_NAME', 'wordpress' );" }
        - { regexp: 'username_here', line: "define( 'DB_USER', 'wordpress_user' );" }
        - { regexp: 'password_here', line: "define( 'DB_PASSWORD', 'wordpress_password' );" }

    - name: Restart Apache service to apply changes
      service:
        name: apache2
        state: restarted
