---
- name: Install and configure Zabbix agent on client
  hosts: localhost
  become: yes
  connection: local
  vars:
    zabbix_server_ip: "{{ zabbix_server_ip }}"  # Server IP wordt doorgegeven vanuit je bash-script
    client_ip: "{{ ansible_default_ipv4.address }}"  # Client IP automatisch verkrijgen

  tasks:
    - name: Install Zabbix agent
      apt:
        name: zabbix-agent
        state: present
      ignore_errors: no

    - name: Configure Zabbix agent
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: "Server={{ zabbix_server_ip }}"  # Zabbix-server IP

    - name: Configure Zabbix agent to allow server to connect
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: "ServerActive={{ zabbix_server_ip }}"  # Actieve server IP

    - name: Configure Zabbix agent with client IP
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: "Hostname={{ client_ip }}"  # Client IP gebruiken

    - name: Restart Zabbix agent
      systemd:
        name: zabbix-agent
        state: restarted

    - name: Enable Zabbix agent to start on boot
      systemd:
        name: zabbix-agent
        enabled: yes
