---
- name: Install Zabbix agent on containers
  hosts: localhost
  become: yes
  connection: local
  vars:
    zabbix_agent_hostname: "{{ inventory_hostname }}"
    zabbix_server_ip: "{{ zabbix_server_ip }}"

  tasks:
    - name: Add Zabbix APT repository key
      apt_key:
        url: https://repo.zabbix.com/zabbix-official-repo.key
        state: present

    - name: Add Zabbix repository for Ubuntu 24.04
      apt_repository:
        repo: "deb https://repo.zabbix.com/zabbix/7.0/ubuntu/ $(lsb_release -sc) main"
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Zabbix agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix agent to connect to the Zabbix server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: "Server={{ zabbix_server_ip }}"
        insertafter: '^#.*Server='

    - name: Configure Zabbix agent Hostname
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Hostname='
        line: "Hostname={{ zabbix_agent_hostname }}"

    - name: Restart Zabbix agent
      service:
        name: zabbix-agent
        state: restarted
        enabled: true
